-- MySQL Script generated by MySQL Workbench
-- Sun Nov 22 17:52:39 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema library
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema library
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `library` DEFAULT CHARACTER SET utf8 ;
USE `library` ;

-- -----------------------------------------------------
-- Table `library`.`author`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library`.`author` (
                                                  `id` INT NOT NULL AUTO_INCREMENT,
                                                  `firstname` VARCHAR(45) NOT NULL,
                                                  `lastname` VARCHAR(45) NOT NULL,
                                                  PRIMARY KEY (`id`),
                                                  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library`.`publisher`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library`.`publisher` (
                                                     `id` INT NOT NULL AUTO_INCREMENT,
                                                     `publisher_name` VARCHAR(45) NOT NULL,
                                                     `publisher_city` VARCHAR(45) NOT NULL,
                                                     PRIMARY KEY (`id`),
                                                     UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library`.`category` (
                                                    `id` INT NOT NULL AUTO_INCREMENT,
                                                    `parent_id` INT NULL,
                                                    `category_name` VARCHAR(45) NOT NULL,
                                                    PRIMARY KEY (`id`),
                                                    UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library`.`book_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library`.`book_status` (
                                                       `id` INT NOT NULL AUTO_INCREMENT,
                                                       `book_status_name` VARCHAR(45) NOT NULL,
                                                       PRIMARY KEY (`id`),
                                                       UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
                                                       UNIQUE INDEX `book_status_name_UNIQUE` (`book_status_name` ASC) VISIBLE)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library`.`book`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library`.`book` (
                                                `id` INT NOT NULL AUTO_INCREMENT,
                                                `book_name` VARCHAR(100) NOT NULL,
                                                `publisher_id` INT NULL,
                                                `publication_year` YEAR NOT NULL,
                                                `category_id` INT NULL,
                                                `book_status_id` INT NULL,
                                                PRIMARY KEY (`id`),
                                                UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
                                                INDEX `fk_book_publisher_idx` (`publisher_id` ASC) VISIBLE,
                                                INDEX `fk_book_category_idx` (`category_id` ASC) VISIBLE,
                                                INDEX `fk_book_book_status_idx` (`book_status_id` ASC) VISIBLE,
                                                CONSTRAINT `fk_book_publisher`
                                                    FOREIGN KEY (`publisher_id`)
                                                        REFERENCES `library`.`publisher` (`id`)
                                                        ON DELETE SET NULL
                                                        ON UPDATE RESTRICT,
                                                CONSTRAINT `fk_book_category`
                                                    FOREIGN KEY (`category_id`)
                                                        REFERENCES `library`.`category` (`id`)
                                                        ON DELETE SET NULL
                                                        ON UPDATE RESTRICT,
                                                CONSTRAINT `fk_book_book_status`
                                                    FOREIGN KEY (`book_status_id`)
                                                        REFERENCES `library`.`book_status` (`id`)
                                                        ON DELETE SET NULL
                                                        ON UPDATE RESTRICT)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library`.`user` (
                                                `id` INT NOT NULL AUTO_INCREMENT,
                                                `username` VARCHAR(45) NOT NULL,
                                                `email` VARCHAR(64) NOT NULL,
                                                `password` VARCHAR(256) NOT NULL,
                                                `firstname` VARCHAR(45) NOT NULL,
                                                `lastname` VARCHAR(45) NOT NULL,
                                                `birthday` DATE NOT NULL,
                                                PRIMARY KEY (`id`),
                                                UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
                                                UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
                                                UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library`.`borrow`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library`.`borrow` (
                                                  `id` INT NOT NULL AUTO_INCREMENT,
                                                  `user_id` INT NULL,
                                                  `book_id` INT NULL,
                                                  `borrow_date` DATE NOT NULL,
                                                  `repayment_date` DATE NOT NULL,
                                                  `return_date` DATE NULL,
                                                  PRIMARY KEY (`id`),
                                                  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
                                                  INDEX `fk_borrow_book_idx` (`book_id` ASC) VISIBLE,
                                                  INDEX `fk_borrow_user_idx` (`user_id` ASC) VISIBLE,
                                                  CONSTRAINT `fk_borrow_book`
                                                      FOREIGN KEY (`book_id`)
                                                          REFERENCES `library`.`book` (`id`)
                                                          ON DELETE SET NULL
                                                          ON UPDATE RESTRICT,
                                                  CONSTRAINT `fk_borrow_user`
                                                      FOREIGN KEY (`user_id`)
                                                          REFERENCES `library`.`user` (`id`)
                                                          ON DELETE SET NULL
                                                          ON UPDATE RESTRICT)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library`.`role` (
                                                `id` INT NOT NULL AUTO_INCREMENT,
                                                `role_name` VARCHAR(45) NOT NULL,
                                                PRIMARY KEY (`id`),
                                                UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
                                                UNIQUE INDEX `role_name_UNIQUE` (`role_name` ASC) VISIBLE)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library`.`user_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library`.`user_role` (
                                                     `role_id` INT NULL,
                                                     `user_id` INT NULL,
                                                     INDEX `fk_user_role_user_idx` (`user_id` ASC) VISIBLE,
                                                     INDEX `fk_user_role_role_idx` (`role_id` ASC) VISIBLE,
                                                     CONSTRAINT `fk_user_role_user`
                                                         FOREIGN KEY (`user_id`)
                                                             REFERENCES `library`.`user` (`id`)
                                                             ON DELETE SET NULL
                                                             ON UPDATE RESTRICT,
                                                     CONSTRAINT `fk_user_role_role`
                                                         FOREIGN KEY (`role_id`)
                                                             REFERENCES `library`.`role` (`id`)
                                                             ON DELETE SET NULL
                                                             ON UPDATE RESTRICT)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library`.`author_book`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library`.`author_book` (
                                                       `author_id` INT NULL,
                                                       `book_id` INT NULL,
                                                       INDEX `fk_author_book_author_idx` (`author_id` ASC) VISIBLE,
                                                       INDEX `fk_author_book_book_idx` (`book_id` ASC) VISIBLE,
                                                       CONSTRAINT `fk_author_book_author`
                                                           FOREIGN KEY (`author_id`)
                                                               REFERENCES `library`.`author` (`id`)
                                                               ON DELETE SET NULL
                                                               ON UPDATE RESTRICT,
                                                       CONSTRAINT `fk_author_book_book`
                                                           FOREIGN KEY (`book_id`)
                                                               REFERENCES `library`.`book` (`id`)
                                                               ON DELETE SET NULL
                                                               ON UPDATE RESTRICT)
    ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
